trigger:
- main

pool:
  name: 'userreg-pool'



stages:
- stage: Build
  jobs:
  - job: Build
    steps:

    - task: Maven@3
      displayName: 'Build finished'
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'Path'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean package'
    - task: CopyFiles@2
      displayName: 'copy the build output'
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
